language: java

dist: bionic

# Use GCC 7 for C++14 support
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

install: 
  # chmod the wrapper to be executable
  - chmod +x ./gradlew
  - ./gradlew --version
  # Install the roboRIO toolchain for cross-compilation
  - ./gradlew installRoboRioToolchain

script:
  - ./gradlew build --scan -s --rerun-tasks

# Enable gradle cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
