language: java

jdk:
  - oraclejdk11
  - openjdk11

# Encrypted Ryver Webhook URL
env:
  global:
    secure: "kD9iWAbkwy2NT94B++VFkn2nsHONfOT8lev8zC75Pn/kAjxmatgelrg1Focg3sIQDfmdeRBF+hxQVna5hDfGMfBRlwGZGHguXb1Mgx9BavsIzLb+JqkmdsQTGcbacGXDBYuNmazBrATBpgMWQDfEZzxt0MI2hDksz7rwZiAzglsOX+o1JVDSFRkZJkgwQh4rILVAwcNFu4afmay6LXtw6ovK4oD9VG5G+h+1YftjjFruHEf2Mtryp2aezEWIS6Yo332pytTfma+ia9JdS9mmNWOWpx5SmTwGs3+lgDgQUnEeUO9URf9/Jdd8WFVLY/vjAYlGUlLWLUqgVH4g+/sqE6OW0NIuKqDH8SocubGM0RmNIr1KDZSQLf8gtdSTWRk9sDkRLbbotbQTtv2UpFxvNacBHBt3+4CtU/3Ba1dHho5w9951KkoCB2yzIM2qNwv1r4RflFXksQFU0ZgwKHdNelTYH7CtkfzwKyXkyNDmiomipJ5LDBL/b29sZW0hzVBv3c/6aNUTNx/A+RuRsYJXTrkYqD5SQWecdc3h4lIwCdlEf6/CKO1V19NerZSvheuQRpjPxJz97YJxoiFZT8dQoRoSYqgjfzj4UPmP6jmXRk3wkKP+fYlJMUaTlIObBphzSAZCZZ64I5PWcvnojbW4jAE6+JaxeoBAdAoTEEe/DxE="

install: 
  # chmod the wrapper to be executable
  - sudo chmod +x ./gradlew
  - ./gradlew --version
  - ./gradlew installRoboRioToolchain

script:
  - ./gradlew build --scan -s

# Enable gradle cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - export SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - >
    curl --request 'POST' 
    --header 'Content-Type: text/plain; charset=utf-8' 
    --data "&#9989; The latest commit pushed to **RobotPathfinder** (commit *$SHORT_COMMIT* on branch *$TRAVIS_BRANCH*) has **passed** CI checks on **$TRAVIS_JDK_VERSION**!"
    $WEBHOOK_URL

after_failure:
  - export SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - >
    curl --request 'POST' 
    --header 'Content-Type: text/plain; charset=utf-8' 
    --data "&#10060; The latest commit pushed to **RobotPathfinder** (commit *$SHORT_COMMIT* on branch *$TRAVIS_BRANCH*) has **failed** CI checks on **$TRAVIS_JDK_VERSION**!" 
    $WEBHOOK_URL